# Generated by Django 3.2.3 on 2021-05-22 16:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unternehmens_name', models.CharField(max_length=120)),
                ('impressium', tinymce.models.HTMLField(verbose_name='impressium')),
                ('datenschutz', tinymce.models.HTMLField(verbose_name='datenschutz')),
                ('logo_img', models.FileField(blank=True, null=True, upload_to='settings/')),
                ('strasse', models.CharField(blank=True, max_length=120)),
                ('strasse2', models.CharField(blank=True, max_length=120)),
                ('ort', models.CharField(blank=True, max_length=120)),
                ('land', models.CharField(blank=True, max_length=120)),
                ('telefon', models.CharField(blank=True, max_length=120)),
                ('email', models.CharField(blank=True, max_length=120)),
                ('plz', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
