# Generated by Django 2.2 on 2021-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.FileField(blank=True, default='placholder_vYebXbG.png', null=True, upload_to='course/'),
        ),
    ]
