# Generated by Django 3.2.3 on 2021-06-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='schema_name',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
