# Generated by Django 2.2 on 2021-04-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('update', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField()),
                ('link_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('photo', models.ImageField(default='teacheravatar.jpg', upload_to='lecture/img/')),
                ('lecture', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='lesson.Lesson')),
            ],
        ),
    ]
