# Generated by Django 3.2.3 on 2021-06-19 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
                ('participations', models.ManyToManyField(related_name='lesson_venues', to='course.Participation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
