# Generated by Django 3.2.3 on 2021-06-22 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_lessonvenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentLessonVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField()),
                ('venure', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='sent_venues', to='lesson.lessonvenue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
