# Generated by Django 3.2.3 on 2021-06-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_sentlessonvenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link_url',
            field=models.URLField(default=True),
        ),
    ]
