# Generated by Django 3.2.3 on 2021-06-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20210623_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
