# Generated by Django 3.2.3 on 2021-05-22 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('preis', models.DecimalField(blank=True, decimal_places=2, default='0,00', max_digits=6)),
                ('description', tinymce.models.HTMLField(verbose_name='description')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('img', models.FileField(blank=True, default='placholder_vYebXbG.png', null=True, upload_to='course/')),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bestellung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=120)),
                ('vorname', models.CharField(blank=True, max_length=120)),
                ('nachnahme', models.CharField(blank=True, max_length=120)),
                ('email', models.CharField(max_length=220)),
                ('adresse', models.CharField(max_length=120)),
                ('plz', models.PositiveSmallIntegerField()),
                ('stadt', models.CharField(max_length=120)),
                ('land', models.CharField(max_length=120)),
                ('tax_nr', models.CharField(max_length=120)),
                ('tel', models.CharField(max_length=120)),
                ('product', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
            ],
        ),
    ]
