# Generated by Django 3.2.3 on 2021-06-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_active',
            field=models.BooleanField(default=False),
        ),
    ]
