# Generated by Django 2.2 on 2021-05-13 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='course/'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
        migrations.CreateModel(
            name='Bestellung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(blank=True, max_length=120)),
                ('vorname', models.CharField(blank=True, max_length=120)),
                ('nachnahme', models.CharField(blank=True, max_length=120)),
                ('email', models.CharField(blank=True, max_length=220)),
                ('adresse', models.CharField(blank=True, max_length=120)),
                ('plz', models.PositiveSmallIntegerField()),
                ('stadt', models.CharField(blank=True, max_length=120)),
                ('land', models.CharField(blank=True, max_length=120)),
                ('tax_nr', models.PositiveSmallIntegerField()),
                ('tel', models.CharField(blank=True, max_length=120)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shopping.Product')),
            ],
        ),
    ]
