# Generated by Django 2.2 on 2021-05-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20210513_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestellung',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='land',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='nachnahme',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='plz',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='stadt',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='tax_nr',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='vorname',
        ),
    ]
