# Generated by Django 2.2 on 2021-05-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20210513_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellung',
            name='nachnahme',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bestellung',
            name='vorname',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
