# Generated by Django 2.2 on 2021-05-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20210513_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellung',
            name='adresse',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='bestellung',
            name='email',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='bestellung',
            name='firma',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='bestellung',
            name='land',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='bestellung',
            name='stadt',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='bestellung',
            name='tel',
            field=models.CharField(max_length=120),
        ),
    ]
