# Generated by Django 2.2 on 2021-05-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20210513_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestellung',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='land',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='plz',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='stadt',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='tax_nr',
        ),
        migrations.RemoveField(
            model_name='bestellung',
            name='tel',
        ),
    ]
