# Generated by Django 2.2 on 2021-05-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20210513_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellung',
            name='adresse',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestellung',
            name='email',
            field=models.CharField(default=1, max_length=220),
            preserve_default=False,
        ),
    ]
