# Generated by Django 2.2 on 2021-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20210513_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellung',
            name='land',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestellung',
            name='plz',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestellung',
            name='stadt',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestellung',
            name='tax_nr',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestellung',
            name='tel',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
