# Generated by Django 2.2 on 2021-05-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20210513_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellung',
            name='tax_nr',
            field=models.CharField(max_length=120),
        ),
    ]
